#!/usr/bin/env python

import os
import re
import subprocess
import sys


PROGRESS_BAR_LEN = 60
QUICK_SEARCH_LIMIT = 1000

verbose_enabled = False
progress_bar_enabled = False
quick_search_enabled = False


def parse_args():
    global verbose_enabled
    global progress_bar_enabled
    global quick_search_enabled

    usage_message = "Usage: %s [-v] [-p] [-q] file_name_pattern1 file_name_pattern2 ...\n" % os.path.basename(sys.argv[0])

    if len(sys.argv) < 2:
        sys.stderr.write(usage_message)
        exit(1)

    argument_set = set(sys.argv[1:])
    if "-v" in argument_set:
        verbose_enabled = True
        argument_set.remove("-v")

    if "-p" in argument_set:
        progress_bar_enabled = True
        argument_set.remove("-p")

    if "-q" in argument_set:
        quick_search_enabled = True
        argument_set.remove("-q")

    if not argument_set:
        sys.stderr.write(usage_message)
        exit(1)

    return argument_set

def print_progress(count, total):
    ratio = count / float(total)
    fill_len = int(round(PROGRESS_BAR_LEN * ratio))
    bar = "%s%s" % ("#" * fill_len, "-" * (PROGRESS_BAR_LEN - fill_len))
    sys.stdout.write("[%s] %s/%s (%s%%)\r" % (bar, count, total, round(ratio * 100, 1)))
    sys.stdout.flush()

def clear_progress(total):
    counter_len = len(str(total)) * 2 + 8
    sys.stdout.write("%s\r" % (" " * (PROGRESS_BAR_LEN + 5 + counter_len)))

def quick_search_filter(file_name_pattern_list, commit_list):
    git_ls_files_command = ["git", "ls-files"]
    file_name_list = subprocess.check_output(git_ls_files_command).split("\n")

    file_name_match_map = {}
    for pattern in file_name_pattern_list:
        file_name_match_list = filter(pattern.search, file_name_list)
        if file_name_match_list:
            file_name_match_map[pattern] = file_name_match_list

    # Ignore quick search if there is no matching file name in the repository.
    # Do not return with an empty list here since the searched file might
    # have been removed in a commit thus without filtering the script might find it.
    if not file_name_match_map:
        sys.stderr.write("Ignore quick search due to pattern mismatch (file not found)\n")
        return commit_list

    file_list_to_filter = []
    for file_name_match_list in file_name_match_map.values():
        if not file_list_to_filter or len(file_list_to_filter) > len(file_name_match_list):
            file_list_to_filter = file_name_match_list[:]

    # Ignore quick search if too much file found for the pattern.
    if len(file_list_to_filter) > QUICK_SEARCH_LIMIT:
        sys.stderr.write("Ignore quick search due to reaching match count limit (%s vs %s)\n" %
                (len(file_list_to_filter), QUICK_SEARCH_LIMIT))
        return commit_list

    git_log_command = ["git", "log", "--oneline"]
    git_log_command.extend(file_list_to_filter)
    commit_list = subprocess.check_output(git_log_command).split("\n")
    return filter(None, commit_list)

def main():
    argument_set = parse_args()

    file_name_pattern_list = []
    for file_name_pattern in argument_set:
        file_name_pattern_list.append(re.compile(file_name_pattern))

    git_log_command = ["git", "log", "--oneline"]
    commit_list = subprocess.check_output(git_log_command).split("\n")
    commit_list = filter(None, commit_list)
    if quick_search_enabled and len(file_name_pattern_list) > 1:
        commit_list = quick_search_filter(file_name_pattern_list, commit_list)

    for i, commit in enumerate(commit_list):
        if progress_bar_enabled:
            print_progress(i, len(commit_list))

        hash = commit.split(" ")[0]

        git_diff_tree_command = ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", hash]
        file_name_list = subprocess.check_output(git_diff_tree_command).split("\n")
        file_name_list = filter(None, file_name_list)

        # Possibly Merge commit
        if not file_name_list:
            if progress_bar_enabled and i + 1 == len(commit_list):
                clear_progress(len(commit_list))
            continue

        matched_file_name_list = []
        for pattern in file_name_pattern_list:
            filtered_file_name_list = filter(pattern.search, file_name_list)
            if not filtered_file_name_list:
                del matched_file_name_list[:]
                break
            matched_file_name_list.extend(filtered_file_name_list)

        if not matched_file_name_list:
            if progress_bar_enabled and i + 1 == len(commit_list):
                clear_progress(len(commit_list))
            continue

        if progress_bar_enabled:
            clear_progress(len(commit_list))
        sys.stdout.write("%s\n" % commit)

        if verbose_enabled:
            for file_name in file_name_list:
                if file_name in matched_file_name_list:
                    print("\t\033[1m\033[91m%s\033[0m" % file_name)
                else:
                    print("\t%s" % file_name)
            print("")

if __name__ == "__main__":
    main()
